defaults:
  - _self_
name: cap_star_uneven
render: true
vis_debug: false
seed: 1
use_komo: false
max_env_steps: 50
env:
  _target_: mops.environments.draw.env.DrawEnv
  stability_check: False
  gui: true
task:
  _target_: mops.environments.draw.tasks.Star
  goal_str: "Draw a five-pointed star. Make sure no lines cross, so for instance do not draw a pentagram."
  task_name: Star
policy:
  _target_: mops.policies.code_as_policies.policy.CaP
  max_feedbacks: 0
  max_csp_samples: 10000
  gaussian_blur: false
  method: cap
updater:
  _target_: mops.environments.utils.DefaultUpdater