defaults:
  - _self_
#  - override hydra/job_logging: colorlog
#  - override hydra/hydra_logging: colorlog

name: deneck_push_wall
render: true
vis_debug: false
seed: 1
use_komo: false
max_env_steps: 50
env:
  _target_: mops.environments.push.env.PushEnv
  stability_check: False
  gui: true
task:
  _target_: mops.environments.push.tasks.PushCircle
  goal_str: "Push the red block to the taget pose."
  task_name: PushCircle
policy:
  _target_: mops.policies.code_as_policies.policy.CaP
  max_feedbacks: 0
  max_csp_samples: 10000
  gaussian_blur: false
  method: cap
updater:
  _target_: mops.environments.utils.DefaultUpdater