defaults:
  - _self_
#  - override hydra/job_logging: colorlog
#  - override hydra/hydra_logging: colorlog

name: deneck_push_wall
render: true
vis_debug: false
seed: 1
use_komo: false
max_env_steps: 50
cma_sigma: 0.05
env:
  _target_: mops.environments.push.env.PushEnv
  stability_check: False
  gui: true
task:
  _target_: mops.environments.push.tasks.PushCircle
  goal_str: "Push the red block to the taget pose."
  task_name: mops_push_wall
policy:
  _target_: mops.policies.mops.policy.MOPS
  max_feedbacks: 2
  max_evals: 1500
  gaussian_blur: false
  method: mops
updater:
  _target_: mops.environments.utils.DefaultUpdater