defaults:
  - _self_
name: mops_star_uneven
render: true
vis_debug: false
seed: 3
use_komo: false
max_env_steps: 50
queryLLM: False
optimizer: cma
cma_sigma: 0.01

env:
  _target_: mops.environments.draw.env.DrawEnv
  stability_check: False
  gui: true
task:
  _target_: mops.environments.draw.tasks.Star
  goal_str: "Draw a five-pointed star. Make sure no lines cross, so for instance do not draw a pentagram."
  task_name: Star
policy:
  _target_: mops.policies.mops.policy.MOPS
  max_feedbacks: 2
  max_evals: 10000
  gaussian_blur: false
  method: mops
updater:
  _target_: mops.environments.utils.DefaultUpdater