defaults:
  - _self_
name: mops_star_uneven
render: true
vis_debug: false
seed: 5
use_komo: false
max_env_steps: 50
queryLLM: False
optimizer: cma
cma_sigma: 0.01
env:
  _target_: mops.environments.draw.env.DrawEnv
  stability_check: False
  gui: true
task:
  _target_: mops.environments.draw.tasks.Pentagon
  goal_str: "Draw an equilateral Pentagon."
  task_name: Pentagon
policy:
  _target_: mops.policies.mops.policy.MOPS
  max_feedbacks: 2
  max_evals: 10000
  gaussian_blur: false
  method: mops
updater:
  _target_: mops.environments.utils.DefaultUpdater