defaults:
  - _self_
#  - override hydra/job_logging: colorlog
#  - override hydra/hydra_logging: colorlog

name: deneck_push_line
render: true
vis_debug: false
seed: 1
use_komo: false
max_env_steps: 50
env:
  _target_: mops.environments.push.env.PushEnv
  stability_check: False
  gui: true
task:
  _target_: mops.environments.push.tasks.PushCircle
  goal_str: "Push the blocks so that they form a circle."
  task_name: PushCircle
policy:
  _target_: mops.policies.proc3s.policy.Proc3s
  max_feedbacks: 2
  max_csp_samples: 10000
  gaussian_blur: false
  method: proc3s
updater:
  _target_: mops.environments.utils.DefaultUpdater